# Generated by Django 3.2.10 on 2022-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address_1",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=265),
        ),
    ]
